### ISSUE TITLE
Dataset structure

### ISSUE THREAD

**Issue by Jumponthemoon** [lsmcolab/Semantic-Segmentation-under-Adverse-Conditions#1]
Hi, good work!

But i came a cross a issue when retrain the network for cityscapes dataset:
![image](https://user-images.githubusercontent.com/39290403/230939824-0d544e21-3de2-4915-a206-e59277a5532e.png)
I doubt that my folder structure is not align with the model,so the model didn't load the image right. Can you provide your dataset structure for the cityscapes? Much appreciate.

**Comment by Jumponthemoon** [comment]
Also, the AWSS dataset seems not working as well. Would you share the preprocess code for the AWSS dataset?

**Comment by A-Kerim** [comment]
Hi @Jumponthemoon,

Thank you for your comment. Sure, I believe we did not change the structure of Cityscapes dataset.   

![image](https://user-images.githubusercontent.com/74662947/231514657-4858f859-1b9c-40ca-87ea-8495ed289fbe.png)

![image](https://user-images.githubusercontent.com/74662947/231514801-0b746f9c-703b-439f-939a-af90512dcc47.png)

You may need to debug your code to be sure that the **num_samples** is not zero.

Well, the provided AWSS can be used directly. It is the preprocessed version. 

All the best,
Kerim

**Comment by Jumponthemoon** [comment]
Thanks for reply!

I fix this error by changing some line in the dataset file such as AWSS and ACDC.

Also, it would be better to mention using "python -m visdom.server" command and change the vis_port number before running the code or else the code will throw out a couple of errors.

The code is running now and thanks for your excellent work.Looking forward to seeing the results.
